version: "3.8"
services:
  db:
    container_name: remix-strapi-base-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./backend/.env
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: remix-strapi-base
    ports:
      - "5432:5432"
    volumes:
      - remix_strapi_base_db:/var/lib/postgresql/data

volumes:
  remix_strapi_base_db: